name: mgp

config-version: 2
version: '0.0.1'

on-run-start:
  - "{{ register_upstream_external_models() }}"

profile: dev

model-paths: ["models"]
test-paths: ["tests"]

target-path: "target"
clean-targets: 
  - target
  - dbt_packages
  - logs

models:
  mgp:
    materialized: external

